# Generated by Django 5.1.3 on 2024-12-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_userprofile_friends_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
    ]
