# Generated by Django 5.1.3 on 2024-12-17 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_userprofile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='sender',
        ),
        migrations.AddField(
            model_name='friend',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='chat.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='user2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='chat.userprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='chat.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='chat.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='friend_requests', to='chat.friendrequest'),
        ),
    ]
