# Generated by Django 5.1.3 on 2024-12-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_friend_user1_alter_friend_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
