# Generated by Django 5.1.3 on 2024-12-17 06:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_chatroom_public_id_userprofile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
